### ISSUE TITLE
If downloaded it will be deleted?

### ISSUE THREAD

**Issue by therealbigdumb** [redeven/BetterTargetPlugin#1]
No matter if I put the master folder into plugins or the folder in master folder it won't get started or straight up deleted D:

**Comment by redeven** [comment]
That's not how you install third-party Dalamud plugins. You go to Dalamud Settings > Experimental > Custom Plugin Repositories, and you add a new line for this repository.
`https://raw.githubusercontent.com/redeven/BetterTargetPlugin/master/repository.json`
Then you install from the Plugins list as normal.
